Update collect.yaml

diff --git a/.github/workflows/collect.yaml b/.github/workflows/collect.yaml
--- a/.github/workflows/collect.yaml
+++ b/.github/workflows/collect.yaml
@@ -1,8 +1,8 @@
 name: Collect
 on:
-  # executed once a week on Sundays at 00:00
+  # 每周日00:00执行一次
   schedule:
-    - cron: "0 9 * * *"
+    - cron: "0 9 * * *"  # 修改为每周日00:00
   workflow_dispatch:
 
 concurrency:
@@ -10,20 +10,19 @@ concurrency:
   cancel-in-progress: true
 
 env:
-  # time zone
+  # 时区
   TZ: Asia/Shanghai
 
-  # github access token
+  # GitHub访问令牌
   GIST_PAT: ${{ secrets.GIST_PAT }}
 
-  # github username and gist id, separated by '/'
+  # GitHub用户名和Gist ID，用'/'分隔
   GIST_LINK: ${{ secrets.GIST_LINK }}
 
-  # the url to the list of airports that you maintain yourself
-  # each line include domain, coupon and invitation code, the domain must be included, and the latter two items are optional
+  # 自定义机场列表的URL
   CUSTOMIZE_LINK: ${{ secrets.CUSTOMIZE_LINK }}
 
-  # include special protocols, such as vless hysteria2 and hysteria
+  # 包含特殊协议
   ENABLE_SPECIAL_PROTOCOLS: ${{ vars.ENABLE_SPECIAL_PROTOCOLS }}
 
 jobs:
@@ -36,36 +35,32 @@ jobs:
         with:
           ref: main
 
-      - name: Prepare
+      - name: Setup Python
         uses: actions/setup-python@v5
         with:
           python-version: "3.x"
           architecture: "x64"
           cache: "pip"
 
-      - name: Install
-        run: pip3 install -r requirements.txt
+      - name: Install Dependencies
+        run: pip install -r requirements.txt  # 使用更简洁的命令
 
-      - name: Check
+      - name: Validate Environment Variables
         run: |
-          if [ -z "$GIST_PAT" ]; then
-              echo "Error: environment 'GIST_PAT' cannot be empty"
+          for var in GIST_PAT GIST_LINK; do
+            if [ -z "${!var}" ]; then
+              echo "Error: environment '$var' cannot be empty"
               exit 1
+            fi
+          done
+
+          if ! echo "$GIST_LINK" | grep -qE '^[^/]+/[^/]+$'; then
+            echo "Error: environment 'GIST_LINK' is not valid, should be 'username/gist_id' format"
+            exit 1
           fi
 
-          if [ -z "$GIST_LINK" ]; then
-              echo "Error: environment 'GIST_LINK' cannot be empty"
-              exit 1
-          fi
-
-          LINK_PARTS=$(echo "$GIST_LINK" | awk -F'/' 'NF==2 && $1!="" && $2!=""')
-          if [ -z "$LINK_PARTS" ]; then
-              echo "Error: environment 'GIST_LINK' is not valid, should be 'username/gist_id' format"
-              exit 1
-          fi
-
-      - name: Collect
+      - name: Collect Data
         run: python -u subscribe/collect.py -a -e -o -s
 
-      - name: Timestamp
+      - name: Add Timestamp
         run: date
